# Generated by Django 4.2 on 2023-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=15)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'billingOffice',
            },
        ),
    ]
